### ISSUE TITLE
现在是不是爬不到了？

### ISSUE THREAD

**Issue by flypigxyz** [Grass-CLP/NXSpider#2]
怎么什么也爬不到啊，下载目录什么也没有啊，显示爬取成功。
![image](https://user-images.githubusercontent.com/50546321/65653150-bc1f2100-e046-11e9-9742-94426693b198.png)

**Comment by LipsonX** [comment]
好久没去看了，可能api更新了。现在也没精力去维护了。仅供学习吧

**Comment by LipsonX** [comment]
close
